
create table if not exists public.loans (
    id bigint generated by default as identity primary key,
    member_name varchar(100) not null,
    book_title varchar(200) not null,
    loan_date date not null,
    due_date date not null,
    return_date date,
    status varchar(20) not null default 'Dipinjam'
        check (status in ('Dipinjam', 'Dikembalikan', 'Terlambat')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint valid_due_date
        check (due_date >= loan_date)
);

alter table public.loans enable row level security;

revoke all on table public.loans from anon, authenticated;

grant all on table public.loans to service_role;

--contoh data
insert into public.loans
    (member_name, book_title, loan_date, due_date, return_date, status)
values
    ('Yassar Fawwas Hernando', 'Praktikum PPB', '2026-10-01', '2026-10-08', null, 'Dipinjam'),
    ('Danish Alfarisy', 'PPB', '2026-09-20', '2026-09-27', null, 'Terlambat'),
    ('Mohamad Rifqi', 'RPL', '2026-09-10', '2026-09-17', '2026-09-16', 'Dikembalikan');
